config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'cities/show'
  get 'cities/index'
  resources :users
  resources :gossips
  resources :commentaries
  resources :sessions
  resources :cities
  root to: 'gossips#index'
  get '/login', to: 'sessions#new'
  get '/contact', to: 'static_pages#contact'
  get '/team', to: 'static_pages#team'
  get '/search', to: 'gossips#search'
  post '/search', to: 'gossips#search_post'
  get '/error_404', to: 'static_pages#error'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
# frozen_string_literal: true

class City < ApplicationRecord
  validates :name, presence: true
  has_many :users
  has_many :gossips, through: :users
  has_many :commentaries, through: :gossips
  has_many :sub_commentaries, through: :commentaries
  has_many :likes, through: :gossips
end

app/models/commentary.rb
# frozen_string_literal: true

class Commentary < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :gossip
  has_many :sub_commentaries, dependent: :destroy
end

app/models/gossip.rb
# frozen_string_literal: true

class Gossip < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :commentaries, dependent: :destroy
  has_many :sub_commentaries, through: :commentaries, dependent: :destroy
  validates :author, presence: true
  validates :title, presence: true
  def self.include_id?(integer)
    Gossip.ids.include?(integer)
  end
end

app/models/like.rb
# frozen_string_literal: true

class Like < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :gossip
end

app/models/sub_commentary.rb
# frozen_string_literal: true

class SubCommentary < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :commentary
  validates :text, presence: true
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_secure_password

  belongs_to :city
  has_many :gossips, foreign_key: 'author_id', class_name: 'Gossip'
  has_many :commentaries, foreign_key: 'author_id', class_name: 'Commentary'
  has_many :sub_commentaries, foreign_key: 'author_id', class_name: 'SubCommentary'
  has_many :likes, foreign_key: 'author_id', class_name: 'Like'
  validates :city, presence: true
  validates :first_name, length: { minimum: 3 }, presence: true
  validates :last_name, length: { minimum: 3 }, presence: true
  validates :user_name, length: { minimum: 6 }, uniqueness: true, presence: true
  validates :email, format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/ }, uniqueness: true
  validates :description, length: { minimum: 100 }
  validates :age, numericality: { greater_than: 0, less_than: 90 }
  validates :password, length: { minimum: 12 }
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  include SessionsHelper
end

app/controllers/cities_controller.rb
# frozen_string_literal: true

class CitiesController < ApplicationController
  def show
    @randomizer = ['https://nsa40.casimages.com/img/2019/02/07/mini_190207103839655476.jpg', 'https://nsa40.casimages.com/img/2019/02/07/mini_190207104119410780.jpg', 'https://nsa40.casimages.com/img/2019/02/07/mini_190207104242937775.jpg', 'https://nsa40.casimages.com/img/2019/02/07/mini_190207104356629054.jpg']
    @city = City.find(params[:id])
  end

  def index
    @cities = City.all
  end
end

app/controllers/commentaries_controller.rb
# frozen_string_literal: true

class CommentariesController < ApplicationController
  def new
    @gossip = Gossip.find(params[:format])
  end

  def create
    @gossip = Gossip.find(params[:format])
    @commentary = Commentary.create(author: current_user, text: commentary_params[:text], gossip: @gossip)
    redirect_to gossip_path(@gossip)
  end

  def update; end

  def destroy; end

  def edit; end

  def show; end

  def index; end

  private

  def commentary_params
    params.permit(:text)
  end
end

app/controllers/gossips_controller.rb
# frozen_string_literal: true

class GossipsController < ApplicationController
  before_action :authenticate_user, only: %i[show create update destroy]

  def index
    @gossips = Gossip.order(id: :asc).all
  end

  def search; end

  def search_post
    if Gossip.include_id?(params[:id].to_s.to_i)
      redirect_to "/gossips/#{params[:id]}"
    else
      redirect_to '/error_404'
    end
    end

  # GET return an HTML form for creating a new potin
  def new; end

  # POST create a new photo
  def create
    @user = current_user
    gossip = Gossip.new
    gossip.author = @user
    gossip.title = params['title']
    gossip.text = params['text']
    gossip.save
    redirect_to '/'
    end

  # Méthode qui récupère le potin concerné et l'envoie à la view show (show.html.erb) pour affichage
  def show
    @gossip = Gossip.find(params[:id].to_s)
    @gossips = Gossip.all
    @id = :id.to_s
    @comments = @gossip.commentaries
  end

  # GET return an HTML form for editing a photo
  def edit
    @gossip = Gossip.find(params[:id])
  end

  # PATCH/PUT update a specific photo
  def update
    @gossip = Gossip.find(params[:id])
    if @gossip.update(title: params[:gossip][:title], text: params[:gossip][:text])
      @gossip.save
      redirect_to '/'
    else
      redirect_to edit_gossip_path
      end
  end

  # DELETE delete a specific photo
  def destroy
    @gossip = Gossip.find(params[:id])
    @gossip.destroy
    redirect_to root_path
    end
end

app/controllers/sessions_controller.rb
# frozen_string_literal: true

class SessionsController < ApplicationController
  def new
    redirect_to user_path(current_user) if current_user
  end

  def create
    @user = User.find_by(email: params[:email])
    if @user&.authenticate(params[:password])
      log_in(@user)
      redirect_to user_path(@user.id)
    else
      flash[:danger] = 'ERROR'
      redirect_to '/login'
    end
  end

  def destroy
    if current_user
      session.delete(:user_id)
      redirect_to root_path
    else
      redirect_to '/login'
    end
  end
end

app/controllers/static_pages_controller.rb
# frozen_string_literal: true

class StaticPagesController < ApplicationController
  def contact; end

  def team; end

  def error; end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  def index; end

  def show
    authenticate_user
    @randomizer = ['https://nsa40.casimages.com/img/2019/02/07/mini_19020711040978981.jpg', 'https://nsa40.casimages.com/img/2019/02/07/mini_190207110601574268.jpg', 'https://nsa40.casimages.com/img/2019/02/07/mini_190207110635325645.jpg', 'https://nsa40.casimages.com/img/2019/02/07/mini_190207111008533839.jpg']
    @user = User.find(params[:id])
  end

  def new; end

  def create
    @user = User.create(password: params[:password])
    @user.city = City.find(params[:city_id])
    @user.first_name = params[:first_name]
    @user.last_name = params[:last_name]
    @user.user_name = params[:user_name]
    @user.age = params[:age]
    @user.description = params[:description]
    @user.email = params[:email]
    if @user.save
      @user.save
      redirect_to '/login'
    else
      redirect_to '/users/new'
    end
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/cities_helper.rb
# frozen_string_literal: true

module CitiesHelper
end

app/helpers/commentaries_helper.rb
# frozen_string_literal: true

module CommentariesHelper
end

app/helpers/gossips_helper.rb
# frozen_string_literal: true

module GossipsHelper
end

app/helpers/searches_helper.rb
# frozen_string_literal: true

module SearchesHelper
end

app/helpers/sessions_helper.rb
# frozen_string_literal: true

module SessionsHelper
  def current_user
    if session[:user_id]
      id = session[:user_id]
      @user = User.find(id)
    end
  end

  def log_in(user)
    session[:user_id] = user.id
  end

  def authenticate_user
    redirect_to '/login' unless current_user
  end
end

app/helpers/static_pages_helper.rb
# frozen_string_literal: true

module StaticPagesHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/cities/index.html.erb
<div class="container my-5">
      <div class="row">
          <div class="col-1">
          </div>

          <div class="col-10">


            <div class="card align-items-center" >
              <img class="card-img-top" src="https://nsa40.casimages.com/img/2019/02/07/190207102811303072.jpg"  alt="Card image cap">
              <div class="card-body">
                <h1 class="card-title text-center">The Gossip Project</h1>
                <p class="card-text text-center">The Gossip Project répertorie tous les potins de THP</p>
              </div>
            </div>

          </div>

          <div class="col-1">
          </div>
      </div>
    </div>

     <div class="container my-5">
      <div class="row">
          <div class="col-1">
          </div>

          <div class="col-10">

            <ul class="list-group">
              <li class="list-group-item d-flex justify-content-between align-items-center">
                <strong> La liste de toutes les villes </strong>
                <span class="badge badge-primary badge-pill"> <%= @cities.length %></span>
              </li>

              <% @cities.each_with_index do |city, index| %>
              <li class="list-group-item d-flex justify-content-between align-items-center">
                <span class="col"><span><%= link_to city.name, city_path((index+1).to_s) %></span></span>

                <span class="col text-right"><span class="badge badge-primary badge-pill"><%= city.gossips.size %></span></span>
              </li>
              <% end %>
            </ul>

          </div>

          <div class="col-1">
</div>
</div>
</div>

app/views/cities/show.html.erb
<br>
<div class="container">
  <div class="row">
    <div class="col-md-9">
      <div class="panel panel-default">
        <div class="panel-body">
          <div class="row">
            <div class="col-md-12 lead">Welcome to <%= @city.name.capitalize %><hr></div>
          </div>
          <div class="row">
      <div class="col-md-4 text-center">
              <img class="img-circle avatar avatar-original" style="-webkit-user-select:none; 
              display:block; margin:auto;" src="<%= @randomizer[rand(4)] %>">
            </div>
            <div class="col-md-8">
              <div class="row">
                <div class="col-md-12">
                  <h1 class="only-bottom-margin"><%= @city.name %></h1>
                </div>
              </div>
              <div class="row">
                <div class="col-md-6">
                  <span class="text-muted"><%= @city.name.capitalize %>'s users number:</span> <%= @city.users.count %><br>
                  <span class="text-muted">Zip:</span> <%= @city.zip_code %><br>
                </div>
                <div class="col-md-6">
                  <div class="activity-mini">
                    <i class="glyphicon glyphicon-comment text-muted"></i>
                  </div>
                  <div class="activity-mini">
                    <i class="glyphicon glyphicon-thumbs-up text-muted"></i>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-md-12">
              <hr>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
          <div class="col-1">
          </div>

          <div class="col-10">
<ul class="list-group">
              <li class="list-group-item d-flex justify-content-between align-items-center">
                <strong> La liste des potins d'ici</strong>
                <span class="badge badge-primary badge-pill"> <%= @city.gossips.length %></span>
              </li>

              <% @city.gossips.each_with_index do |gossip| %>
              <li class="list-group-item d-flex justify-content-between align-items-center">
                <%= link_to gossip.title, gossip_path(gossip.id.to_s) %>

                <span class="badge badge-primary badge-pill"> <%= link_to "lien", "/gossips/#{gossip.id.to_s}", {:style=>'color:#FFFFFF'} %></span>
              </li>
              <% end %>
            </ul>

          </div>

          <div class="col-1">
          </div>
        </div>



</div>

app/views/commentaries/create.html.erb
<h1>Commentaries#create</h1>
<p>Find me in app/views/commentaries/create.html.erb</p>

app/views/commentaries/destroy.html.erb
<h1>Commentaries#destroy</h1>
<p>Find me in app/views/commentaries/destroy.html.erb</p>

app/views/commentaries/edit.html.erb
<h1>Commentaries#edit</h1>
<p>Find me in app/views/commentaries/edit.html.erb</p>

app/views/commentaries/index.html.erb
<h1>Commentaries#index</h1>
<p>Find me in app/views/commentaries/index.html.erb</p>

app/views/commentaries/new.html.erb
<div class="container">
<h1>Que serait une plateforme de gossiping sans commentaires? 😏</h1>
<div class="card">
  <div class="card-header">
    Gossip n°<%= @gossip.id %> :
  </div>
  <div class="card-body">
    <blockquote class="blockquote mb-0">
      <p><%= @gossip.title %><br /><br /><%= @gossip.text %></p>
      <footer class="blockquote-footer"><%= @gossip.author.first_name + " " + @gossip.author.last_name %> <cite title="Source Title"><%= @gossip.author.city.name %></cite></footer>
    </blockquote>
  </div>
</div>
<p><form action='<%= commentaries_path %>' method='POST'>
    <input type='hidden' name='authenticity_token' value='<%= form_authenticity_token %>'>

  <div class='form-group'>
  <label for='title'>Texte :</label>
  <textarea type="text" class="form-control" name='text' placeholder="Your commentary" rows="3"></textarea>
  </div>
<button type="submit" class="btn btn-primary">Submit</button>

</form></p>
</div>

app/views/commentaries/show.html.erb
<h1>Commentaries#show</h1>
<p>Find me in app/views/commentaries/show.html.erb</p>

app/views/commentaries/update.html.erb
<h1>Commentaries#update</h1>
<p>Find me in app/views/commentaries/update.html.erb</p>

app/views/gossips/create.html.erb
<h1>Gossips#create</h1>
<p>Find me in app/views/gossips/create.html.erb</p>

app/views/gossips/delete.html.erb
<h1>Gossips#delete</h1>
<p>Find me in app/views/gossips/delete.html.erb</p>

app/views/gossips/edit.html.erb
<div class="container">
<h1>Edit potin n° <%= params[:id] %></h1>
<h2><sub>No efforts on the front, sorry i was sleeping yesterday</sub></h2>
<p><%= form_for @gossip do |k| %>

    <input type='hidden' name='authenticity_token' value='<%= form_authenticity_token %>'>

  <div class='form-group'>
  <label for='title'>Titre</label>
  <%= k.text_field :title, class: "form-control" %>
  </div>

  <div class="form-group">
    <label for="exampleTextarea">Corps du potin</label>
    <%= k.text_area :text, class: "form-control" %>
  </div>

<button type="submit" class="mr-5 btn btn-primary">Submit</button>

<% end %></p>
</div>

app/views/gossips/index.html.erb
    <div class="container my-5">
      <div class="row">
          <div class="col-1">
          </div>

          <div class="col-10">


            <div class="card align-items-center" >
              <img class="card-img-top" src="https://images.unsplash.com/photo-1472746729193-36ad213ac4a5?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1000&q=80"  alt="Card image cap">
              <div class="card-body">
                <h1 class="card-title text-center">The Gossip Project</h1>
                <p class="card-text text-center">The Gossip Project répertorie tous les potins de THP</p>
              </div>
            </div>

            <div class="card-body d-flex justify-content-between">
              <%= link_to "Crée un potin", new_gossip_path %>
							<%= link_to "Liste des villes", cities_path %>
              <%= link_to "Choisis un potin avec son ID!" , search_path %> <!-- Je mets 0 car on ne connait pas l'id du gossip à créer -->
            </div>

          </div>

          <div class="col-1">
          </div>
      </div>
    </div>

     <div class="container my-5">
      <div class="row">
          <div class="col-1">
          </div>

          <div class="col-10">

            <ul class="list-group">
              <li class="list-group-item d-flex justify-content-between align-items-center">
                <strong> La liste de tous les potins </strong>
                <span class="badge badge-primary badge-pill"> <%= Gossip.all.length %></span>
              </li>
        
              <% Gossip.all.each_with_index do |gossip, index| %>
              <li class="list-group-item d-flex justify-content-between align-items-center">
                <span class="col"><span><%= link_to gossip.title, gossip_path((index+1).to_s) %></span></span>
                
                <span class="col text-right"><span class="badge badge-primary badge-pill">par <%= link_to gossip.author.user_name, user_path(gossip.author.id), {:style=>'color:#FFFFFF'} %> <%= link_to "(#{gossip.author.city.name})", city_path(gossip.author.city.id), {:style=>'color:#FFFFFF'} %></span></span>
              </li>
              <% end %>
            </ul>

          </div>

          <div class="col-1">
          </div>
        </div>
      </div>

app/views/gossips/new.html.erb
<div class="container">
<h1>Create a new potin !</h1>
<h2><sub>No efforts on the front, sorry i was sleeping yesterday</sub></h2>
<p><form action='<%= gossips_path %>' method='POST'>
		<input type='hidden' name='authenticity_token' value='<%= form_authenticity_token %>'>

	<div class='form-group'>
	<label for='title'>Titre</label>
	<input type="sting" class="form-control" name='title' id="title" placeholder="Title">
	</div>

	<div class="form-group">
    <label for="exampleTextarea">Corps du potin</label>
    <textarea placeholder="Votre potin ici" class="form-control" name='text' id="exampleTextarea" rows="3"></textarea>
  </div>

<button type="submit" class="btn btn-primary">Submit</button>

</form></p>
</div>

app/views/gossips/search.html.erb
<h1 class='offset-md-5 mt-5'>Recherche de potin par ID</h1>
<div class='container h-50'>
<div class='row h-100 justify-content-center'>
<form class="form-inline align-middle" action='<%= search_path %>' method='POST'>
  <div class="form-group mb-2 mt-3">
    <label for="staticEmail2" class="sr-only">Email</label>
		<input type="text" name='id' class="form-control-plaintext" id="staticEmail2" value="Recherche par id :">
  </div>
  <div class="form-group mx-sm-3 mb-2">
    <label for="inputPassword2" class="sr-only">Password</label>
		<input type='hidden' name='authenticity_token' value='<%= form_authenticity_token %>'>
    <input type="text" name="id" class="form-control" id="inputPassword2" placeholder="Gossip n°.">
  </div>
  <button type="submit" class="btn btn-primary mb-2">Chercher</button>
</form>
</div>
</div>

app/views/gossips/show.html.erb
    <div class="container my-5">
      <div class="row">
          <div class="col-1">
          </div>

          <div class="col-10">


            <div class="card align-items-center" >
              <img class="card-img-top" src="https://images.unsplash.com/photo-1482356432770-3a99f07aba35?ixlib=rb-1.2.1&ix@id=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1000&q=80"  alt="Card image cap">
              <div class="card-body">
                <h1 class="card-title">Potin d'id <%= params[:id] %></h1>
                <p class="card-text">Son auteur : <%= link_to "#{@gossip.author.user_name}", user_path %><br />Son titre : <%= @gossip.title %><br /> Son contenu : <%= @gossip.text %></p>
                <p><a class="card-text" href="/"> Lien pour revenir à la page d'accueil</a></p>
                 <p><%= link_to "Pour éditer le potin, c'est ici", edit_gossip_path %></p>
<p><a href=<%= "/gossips/#{params[:id].to_s}" %> data-confirm="Cette action est irréversible.", data-method="DELETE">Supprimer</a>
              </div>
            </div>
 

            <div class="card-body">
              <%= link_to "Crée un commentaire", new_commentary_path(@gossip) %>
            </div>

          </div>

          <div class="col-1">
          </div>
      </div>
    </div>

     <div class="container my-5">
      <div class="row">
          <div class="col-1">
          </div>

          <div class="col-10">

            <ul class="list-group">
              <li class="list-group-item d-flex justify-content-between align-items-center">
                <strong> Commentaires </strong>
                <span class="badge badge-primary badge-pill"> <%= @comments.length %></span>
              </li>
        
              <% @comments.each_with_index do |comment, index| %>
              <li class="list-group-item d-flex justify-content-between align-items-center">
                <%= comment.text %>
                <span class="col text-right"><span class="badge badge-primary badge-pill">par <%= link_to comment.author.user_name, user_path(comment.author.id), {:style=>'color:#FFFFFF'} %> <%= "(#{comment.author.city.name})" %></span></span>
              </li>
              <% end %>
            </ul>

          </div>

          <div class="col-1">
          </div>
        </div>
      </div>

app/views/static_pages/contact.html.erb
<div class='container col-12 col-sm-12 col-md-12 col-lg-12 h-25'>
  <div class='row h-100'>
    <div class='col-2 col-sm-2 col-md-2 col-lg-2 bg-primary'>
    </div>
    <div class='col-10 col-sm-10 col-md-10 col-lg-10'>
      <div class='row'>
      <div class='col offset-md-1 mt-5'>
	<h1>Contact</h1>
      <div class='row h-100'>
      <div class='col'>
			<div class='container-fluid'>
	  <ul class='h-100'>
	    <li><em>Thibaut</em> : 06 86 45 42 12</li>
	    <li><em>Auguste</em> : 07 83 89 27 32</li></ul>
	  </div>
</div>
</div>
      </div>
      </div>
      </div>
  </div>
</div>

app/views/static_pages/team.html.erb
<div class='container col-12 col-sm-12 col-md-12 col-lg-12 h-75'>
  <div class='row h-100'>
    <div class='col-2 col-sm-2 col-md-2 col-lg-2 bg-primary'>
    </div>
    <div class='col-10 col-sm-10 col-md-10 col-lg-10>
      <div class='row'>
      <div class='col offset-md-1 mt-5 h-50'>
	<h1>We're happy to welcome you on this page</h1>
	<h2>Presentation</h2>
      </div>
      <div class='row h-100'>
	<p class='h-100 offset-md-2'>Helly guys, I'm Thibaut, and this is my brand new website designed with Auguste !!</p>
      </div>
      </div>
      </div>
      </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="container">
<h1>Welcome</h1>
<h2>Before you can add some gossips to the front page, you have to fill a 2 minutes formulary to let us know you  <sub>Because yes ! We're interested in you ^-^</sub></h2>
<p><form action='<%= users_path %>' method='POST'>

    <input type='hidden' name='authenticity_token' value="<%= form_authenticity_token %>">

  <div class='form-group'>
  <label for='title'>First name</label>
  <input type="string" class="form-control" name='first_name' placeholder="John">
  </div>

  <div class='form-group'>
  <label for='title'>Last name</label>
  <input type="string" class="form-control" name='last_name' placeholder="Doe">
  </div>

    <div class="form-group">
    <label for="exampleFormControlSelect1">City</label>
    <select class="form-control" name="city_id">
      <% City.all.each do |city| %>
      <option value=<%= city.id %> ><%= city.name %></option>
      <% end %>
    </select>
  </div>

  <div class='form-group'>
  <label for='title'>Username (A.K.A)</label>
  <input type="string" class="form-control" name='user_name' placeholder="~Jdoe193~">
  </div>

  <div class='form-group'>
  <label for='title'>Email</label>
  <input type="string" class="form-control" name='email' placeholder="hacking@proj.ect">
  </div>

  <div class='form-group'>
  <label for='title'>Age</label>
  <input type="string" class="form-control" name='age' placeholder="27">
  </div>

	<div class="form-group">
    <label for="exampleInputPassword1">Password</label>
    <input type="password" name="password" class="form-control" placeholder="$723GabbKrs1^*5£5">
  </div>

	<div class="form-group">
    <label for="exampleInputPassword1">Please confirm password</label>
    <input type="password" class="form-control" name="password_confirmation" placeholder="$723GabbKrs1^*5£5">
  </div>

  <div class="form-group">
    <label for="exampleTextarea">Description</label>
    <textarea class="form-control" name='description' rows="3"></textarea>
  </div>

<button type="submit" class="btn btn-primary">Submit</button>

</p>
</div>

app/views/users/show.html.erb
<br>
<div class="container">
  <div class="row">
    <div class="col-md-9">
      <div class="panel panel-default">
        <div class="panel-body">
          <div class="row">
            <div class="col-md-12 lead">User profile<hr></div>
          </div>
          <div class="row">
			<div class="col-md-4 text-center">
              <img class="img-circle avatar avatar-original" style="-webkit-user-select:none; 
              display:block; margin:auto;" src="<%= @randomizer[rand(4)] %>">
            </div>
            <div class="col-md-8">
              <div class="row">
                <div class="col-md-12">
                  <h1 class="only-bottom-margin"><%= User.find(params[:id]).user_name %></h1>
                </div>
              </div>
              <div class="row">
                <div class="col-md-6">
                  <span class="text-muted">Email:</span> <%= User.find(params[:id]).email %><br>
                  <span class="text-muted">City:</span> <%= link_to User.find(params[:id]).city.name, city_path(User.find(params[:id]).city) %><br>
                  <span class="text-muted">age:</span> <%= User.find(params[:id]).age %><br><br>
                  <small class="text-muted">Created at: <%= User.find(params[:id]).created_at.to_time %></small>
                </div>
                <div class="col-md-6">
                  <div class="activity-mini">
                    <i class="glyphicon glyphicon-comment text-muted"></i> 
                  </div>
                  <div class="activity-mini">
                    <i class="glyphicon glyphicon-thumbs-up text-muted"></i> 
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-md-12">
              <hr>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
	<div class="row">
          <div class="col-1">
          </div>

          <div class="col-10">

            <ul class="list-group">
              <li class="list-group-item d-flex justify-content-between align-items-center">
                <strong> La liste de tous mes potins </strong>
                <span class="badge badge-primary badge-pill"> <%= User.find(params[:id]).gossips.length %></span>
              </li>

              <% User.find(params[:id]).gossips.each_with_index do |gossip| %>
              <li class="list-group-item d-flex justify-content-between align-items-center">
                <%= link_to gossip.title, gossip_path(gossip.id.to_s) %>

                <span class="badge badge-primary badge-pill"> <%= link_to "lien", "/gossips/#{gossip.id.to_s}", {:style=>'color:#FFFFFF'} %></span>
              </li>
              <% end %>
            </ul>

          </div>

          <div class="col-1">
          </div>
        </div>



</div>