config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'cities/show'
  get 'cities/index'
  resources :users
  resources :gossips
  resources :commentaries
  resources :sessions
  resources :cities
  root to: 'gossips#index'
  get '/login', to: 'sessions#new'
  get '/contact', to: 'static_pages#contact'
  get '/team', to: 'static_pages#team'
  get '/search', to: 'gossips#search'
  post '/search', to: 'gossips#search_post'
  get '/error_404', to: 'static_pages#error'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
# frozen_string_literal: true

class City < ApplicationRecord
  validates :name, presence: true
  has_many :users
  has_many :gossips, through: :users
  has_many :commentaries, through: :gossips
  has_many :sub_commentaries, through: :commentaries
  has_many :likes, through: :gossips
end

app/models/commentary.rb
# frozen_string_literal: true

class Commentary < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :gossip
  has_many :sub_commentaries, dependent: :destroy
end

app/models/gossip.rb
# frozen_string_literal: true

class Gossip < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :commentaries, dependent: :destroy
  has_many :sub_commentaries, through: :commentaries, dependent: :destroy
  validates :author, presence: true
  validates :title, presence: true
  def self.include_id?(integer)
    Gossip.ids.include?(integer)
  end
end

app/models/like.rb
# frozen_string_literal: true

class Like < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :gossip
end

app/models/sub_commentary.rb
# frozen_string_literal: true

class SubCommentary < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :commentary
  validates :text, presence: true
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_secure_password

  belongs_to :city
  has_many :gossips, foreign_key: 'author_id', class_name: 'Gossip'
  has_many :commentaries, foreign_key: 'author_id', class_name: 'Commentary'
  has_many :sub_commentaries, foreign_key: 'author_id', class_name: 'SubCommentary'
  has_many :likes, foreign_key: 'author_id', class_name: 'Like'
  validates :city, presence: true
  validates :first_name, length: { minimum: 3 }, presence: true
  validates :last_name, length: { minimum: 3 }, presence: true
  validates :user_name, length: { minimum: 6 }, uniqueness: true, presence: true
  validates :email, format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/ }, uniqueness: true
  validates :description, length: { minimum: 100 }
  validates :age, numericality: { greater_than: 0, less_than: 90 }
  validates :password, length: { minimum: 12 }
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  include SessionsHelper
end

app/controllers/cities_controller.rb
# frozen_string_literal: true

class CitiesController < ApplicationController
  def show
    @randomizer = ['https://nsa40.casimages.com/img/2019/02/07/mini_190207103839655476.jpg', 'https://nsa40.casimages.com/img/2019/02/07/mini_190207104119410780.jpg', 'https://nsa40.casimages.com/img/2019/02/07/mini_190207104242937775.jpg', 'https://nsa40.casimages.com/img/2019/02/07/mini_190207104356629054.jpg']
    @city = City.find(params[:id])
  end

  def index
    @cities = City.all
  end
end

app/controllers/gossips_controller.rb
# frozen_string_literal: true

class GossipsController < ApplicationController
  before_action :authenticate_user, only: %i[show create update destroy]

  def index
    @gossips = Gossip.order(id: :asc).all
  end

  def search; end

  def search_post
    if Gossip.include_id?(params[:id].to_s.to_i)
      redirect_to "/gossips/#{params[:id]}"
    else
      redirect_to '/error_404'
    end
    end

  # GET return an HTML form for creating a new potin
  def new; end

  # POST create a new photo
  def create
    @user = current_user
    gossip = Gossip.new
    gossip.author = @user
    gossip.title = params['title']
    gossip.text = params['text']
    gossip.save
    redirect_to '/'
    end

  # Méthode qui récupère le potin concerné et l'envoie à la view show (show.html.erb) pour affichage
  def show
    @gossip = Gossip.find(params[:id].to_s)
    @gossips = Gossip.all
    @id = :id.to_s
    @comments = @gossip.commentaries
  end

  # GET return an HTML form for editing a photo
  def edit
    @gossip = Gossip.find(params[:id])
  end

  # PATCH/PUT update a specific photo
  def update
    @gossip = Gossip.find(params[:id])
    if @gossip.update(title: params[:gossip][:title], text: params[:gossip][:text])
      @gossip.save
      redirect_to '/'
    else
      redirect_to edit_gossip_path
      end
  end

  # DELETE delete a specific photo
  def destroy
    @gossip = Gossip.find(params[:id])
    @gossip.destroy
    redirect_to root_path
    end
end

app/controllers/sessions_controller.rb
# frozen_string_literal: true

class SessionsController < ApplicationController
  def new
    redirect_to user_path(current_user) if current_user
  end

  def create
    @user = User.find_by(email: params[:email])
    if @user&.authenticate(params[:password])
      log_in(@user)
      redirect_to user_path(@user.id)
    else
      flash[:danger] = 'ERROR'
      redirect_to '/login'
    end
  end

  def destroy
    if current_user
      session.delete(:user_id)
      redirect_to root_path
    else
      redirect_to '/login'
    end
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  def index; end

  def show
    authenticate_user
    @randomizer = ['https://nsa40.casimages.com/img/2019/02/07/mini_19020711040978981.jpg', 'https://nsa40.casimages.com/img/2019/02/07/mini_190207110601574268.jpg', 'https://nsa40.casimages.com/img/2019/02/07/mini_190207110635325645.jpg', 'https://nsa40.casimages.com/img/2019/02/07/mini_190207111008533839.jpg']
    @user = User.find(params[:id])
  end

  def new; end

  def create
    @user = User.create(password: params[:password])
    @user.city = City.find(params[:city_id])
    @user.first_name = params[:first_name]
    @user.last_name = params[:last_name]
    @user.user_name = params[:user_name]
    @user.age = params[:age]
    @user.description = params[:description]
    @user.email = params[:email]
    if @user.save
      @user.save
      redirect_to '/login'
    else
      redirect_to '/users/new'
    end
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/cities_helper.rb
# frozen_string_literal: true

module CitiesHelper
end

app/helpers/commentaries_helper.rb
# frozen_string_literal: true

module CommentariesHelper
end

app/helpers/gossips_helper.rb
# frozen_string_literal: true

module GossipsHelper
end

app/helpers/searches_helper.rb
# frozen_string_literal: true

module SearchesHelper
end

app/helpers/sessions_helper.rb
# frozen_string_literal: true

module SessionsHelper
  def current_user
    if session[:user_id]
      id = session[:user_id]
      @user = User.find(id)
    end
  end

  def log_in(user)
    session[:user_id] = user.id
  end

  def authenticate_user
    redirect_to '/login' unless current_user
  end
end

app/helpers/static_pages_helper.rb
# frozen_string_literal: true

module StaticPagesHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FullGossip</title>
	<%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">

   <!-- QUICKSAND FONT FROM GOOGLE FONT -->
    <link href="https://fonts.googleapis.com/css?family=Quicksand" rel="stylesheet">

   <!-- Bootstrap CSS -->
   <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
  </head>

  <body>
    <!-- NAVBAR -->
   <nav class="navbar navbar-expand-lg navbar-light bg-light"> <a class="navbar-brand">
          <i class="fab fa-google text-primary"></i> </a>
         THE GOSSIP PROJECT        
      </a>


  <div class="navbar collapse navbar-collapse" id="navbarNavAltMarkup">

    <div class="navbar-nav ml-auto">

      <a class="nav-item nav-link border border-success rounded" <%= link_to "Home",  root_path %></a>

			<a class="nav-item nav-link border border-success rounded" <%= link_to "Sign up",  new_user_path %></a>

			<a class="nav-item nav-link border border-success rounded" <%= link_to "Team",  team_path %></a>
      <a class="nav-item nav-link border border-success rounded" <%= link_to "Contact",  contact_path %></a>
<% if current_user then %>
		<%= link_to session_path(session), method: :delete, class: "nav-item nav-link border border-success rounded" do
"Se déconnecter" end %>
<% else %>
<%= link_to "/login", class: "nav-item nav-link border border-success rounded" do "Sign in" end %>
<% end %>

    </div>
  </nav>

    <style>
     body {
    font-family: 'Quicksand', sans-serif;
    font-size: 20px;
    height: 100vh;
      }
   </style>



    <%= yield %>



    <footer class="footer mt-auto py-auto">
      <div class="container">
        <span class="text-muted">Made in Marseille with love</span>
      </div>
    </footer>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
    
  </body>
</html>